"""Pydantic request/response schemas. Re-exported for backward compatibility."""

from src.schemas.auth import (
    SignupRequest,
    SignupResponse,
    LoginRequest,
    TokenResponse,
    VerifyEmailRequest,
    VerifyEmailResponse,
    ResendVerificationRequest,
    ResendVerificationResponse,
)
from src.schemas.profile import (
    PersonResponse,
    PatchProfileRequest,
    VisibilitySettingsResponse,
    PatchVisibilityRequest,
)
from src.schemas.bio import PastCompanyItem, BioResponse, BioCreateUpdate
from src.schemas.contact import ContactDetailsResponse, PatchContactRequest
from src.schemas.credits import CreditsResponse, PurchaseCreditsRequest, LedgerEntryResponse
from src.schemas.builder import (
    RawExperienceCreate,
    RawExperienceResponse,
    RewriteTextResponse,
    TranslateTextResponse,
    CardFamilyV1Response,
    DraftSetV1Response,
    FillFromTextRequest,
    FillFromTextResponse,
    CommitDraftSetRequest,
    ExperienceCardCreate,
    ExperienceCardPatch,
    ExperienceCardResponse,
    ExperienceCardChildPatch,
    ExperienceCardChildResponse,
    CardFamilyResponse,
)
from src.schemas.search import (
    SearchRequest,
    PersonSearchResult,
    SearchResponse,
    PersonProfileResponse,
    SavedSearchItem,
    SavedSearchesResponse,
    UnlockContactRequest,
    UnlockContactResponse,
)
from src.schemas.discover import (
    PersonListItem,
    PersonListResponse,
    PersonPublicProfileResponse,
    UnlockedCardItem,
    UnlockedCardsResponse,
)

__all__ = [
    "SignupRequest",
    "SignupResponse",
    "LoginRequest",
    "TokenResponse",
    "VerifyEmailRequest",
    "VerifyEmailResponse",
    "ResendVerificationRequest",
    "ResendVerificationResponse",
    "PersonResponse",
    "PatchProfileRequest",
    "VisibilitySettingsResponse",
    "PatchVisibilityRequest",
    "PastCompanyItem",
    "BioResponse",
    "BioCreateUpdate",
    "ContactDetailsResponse",
    "PatchContactRequest",
    "CreditsResponse",
    "PurchaseCreditsRequest",
    "LedgerEntryResponse",
    "RawExperienceCreate",
    "RawExperienceResponse",
    "RewriteTextResponse",
    "TranslateTextResponse",
    "CardFamilyV1Response",
    "DraftSetV1Response",
    "FillFromTextRequest",
    "FillFromTextResponse",
    "CommitDraftSetRequest",
    "ExperienceCardCreate",
    "ExperienceCardPatch",
    "ExperienceCardResponse",
    "ExperienceCardChildPatch",
    "ExperienceCardChildResponse",
    "CardFamilyResponse",
    "SearchRequest",
    "PersonSearchResult",
    "SearchResponse",
    "PersonProfileResponse",
    "SavedSearchItem",
    "SavedSearchesResponse",
    "UnlockContactRequest",
    "UnlockContactResponse",
    "PersonListItem",
    "PersonListResponse",
    "PersonPublicProfileResponse",
    "UnlockedCardItem",
    "UnlockedCardsResponse",
]
